name: My littre path
on: [push]
env: 
  variable: "Je suis une variable mere"
jobs: 
  jobs1: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: hello world
      run: echo $variable
  jobs2: 
    runs-on: ubuntu-latest
    env: 
      age: 100
    steps:
    - uses: actions/checkout@v3
    - name: hello world
      run: echo $age
